<a href="https://colab.research.google.com/github/Raphael8112/data-preprocessing/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#upload the data
from google.colab import files
file=files.upload()

Saving country_vaccinations.csv to country_vaccinations (1).csv

In [2]:
#library importations
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [3]:
#load the data
ds=pd.read_csv('/content/country_vaccinations.csv')
ds.head()

       country iso_code  ...                source_name            source_website
0  Afghanistan      AFG  ...  World Health Organization  https://covid19.who.int/
1  Afghanistan      AFG  ...  World Health Organization  https://covid19.who.int/
2  Afghanistan      AFG  ...  World Health Organization  https://covid19.who.int/
3  Afghanistan      AFG  ...  World Health Organization  https://covid19.who.int/
4  Afghanistan      AFG  ...  World Health Organization  https://covid19.who.int/

[5 rows x 15 columns]

In [4]:
#dataset information
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25862 entries, 0 to 25861
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              25862 non-null  object
 1   iso_code                             25862 non-null  object
 2   date                                 25862 non-null  object
 3   total_vaccinations                   14522 non-null  float64
 4   people_vaccinated                    13762 non-null  float64
 5   people_fully_vaccinated              11041 non-null  float64
 6   daily_vaccinations_raw               12003 non-null  float64
 7   daily_vaccinations                   25595 non-null  float64
 8   total_vaccinations_per_hundred       14522 non-null  float64
 9   people_vaccinated_per_hundred        13762 non-null  float64
 10  people_fully_vaccinated_per_hundred  11041 non-null  float64
 11  daily_vaccinations_per_million       25595 non-null  float64
 12  vaccines                             25862 non-null  object
 13  source_name                          25862 non-null  object
 14  source_website                       25862 non-null  object
dtypes: float64(9), object(6)
memory usage: 3.0+ MB

In [5]:
#check for null values
ds.isnull().sum()

country                                    0
iso_code                                   0
date                                       0
total_vaccinations                     11340
people_vaccinated                      12100
people_fully_vaccinated                14821
daily_vaccinations_raw                 13859
daily_vaccinations                       267
total_vaccinations_per_hundred         11340
people_vaccinated_per_hundred          12100
people_fully_vaccinated_per_hundred    14821
daily_vaccinations_per_million           267
vaccines                                   0
source_name                                0
source_website                             0
dtype: int64

In [6]:
#check for class inbalance
ds['country'].value_counts()

country
Norway                             201
Scotland                           193
Canada                             189
China                              188
Russia                             188
                                  ...
Burkina Faso                        13
Chad                                 1
Bonaire Sint Eustatius and Saba      1
Pitcairn                             1
Turkmenistan                         1
Name: count, Length: 217, dtype: int64

In [8]:
#drop null values
ds.dropna(inplace=True)

In [9]:
#drop duplicated data
ds.drop_duplicates(inplace=True)

In [11]:
#drop unessecary columns
ds.drop(['source_name','source_website','isa_code','date'],axis=1, errors='ignore', inplace=True)

In [12]:
#convert categorial columns
le=LabelEncoder()
ds['country']=le.fit_transform(ds['country'])
ds['vaccines']=le.fit_transform(ds['vaccines'])

In [13]:
ds.head()

     country iso_code  ...  daily_vaccinations_per_million  vaccines
94         0      AFG  ...                           167.0         3
101        0      AFG  ...                           136.0         3
152        1      ALB  ...                            88.0        32
234        1      ALB  ...                          4225.0        32
235        1      ALB  ...                          3777.0        32

[5 rows x 12 columns]

In [14]:
ds.columns

Index(['country', 'iso_code', 'total_vaccinations', 'people_vaccinated',
       'people_fully_vaccinated', 'daily_vaccinations_raw',
       'daily_vaccinations', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'daily_vaccinations_per_million', 'vaccines'],
      dtype='object')

In [16]:
ds.drop(['daily_vaccination_raw','total_vaccination_per_hundred','people_vaccinated_per_hundred','people_fully_vaccinated_per_hundred','daily_vaccination_per_million'],axis=1,errors='ignore',inplace=True)

In [17]:
ds.head()

     country iso_code  ...  daily_vaccinations_per_million  vaccines
94         0      AFG  ...                           167.0         3
101        0      AFG  ...                           136.0         3
152        1      ALB  ...                            88.0        32
234        1      ALB  ...                          4225.0        32
235        1      ALB  ...                          3777.0        32

[5 rows x 10 columns]